2024-12-03 20:14:08,938 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:14:08,963 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:14:10,603 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:14:10,607 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:14:17,899 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 20:14:21,590 - FlaskAppLogger - ERROR - Error deleting log: 66
2024-12-03 20:14:40,246 - FlaskAppLogger - ERROR - Error deleting log: 67
2024-12-03 20:16:18,902 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:16:18,931 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:16:26,814 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:16:26,820 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:17:39,632 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:17:39,637 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:17:43,851 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:17:43,858 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:17:51,470 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 20:17:54,470 - FlaskAppLogger - ERROR - Error deleting log 65: Class 'builtins.int' is not mapped
2024-12-03 20:17:57,402 - FlaskAppLogger - ERROR - Error deleting log 66: Class 'builtins.int' is not mapped
2024-12-03 20:18:09,436 - FlaskAppLogger - ERROR - Error deleting log 65: Class 'builtins.int' is not mapped
2024-12-03 20:18:09,626 - FlaskAppLogger - ERROR - Error deleting log 65: Class 'builtins.int' is not mapped
2024-12-03 20:18:09,819 - FlaskAppLogger - ERROR - Error deleting log 65: Class 'builtins.int' is not mapped
2024-12-03 20:18:09,985 - FlaskAppLogger - ERROR - Error deleting log 65: Class 'builtins.int' is not mapped
2024-12-03 20:18:10,161 - FlaskAppLogger - ERROR - Error deleting log 65: Class 'builtins.int' is not mapped
2024-12-03 20:18:35,642 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:18:35,648 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:18:38,841 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:18:38,846 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:18:41,918 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:18:41,924 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:18:46,551 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:18:46,556 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 20:18:49,725 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-03 20:18:52,717 - FlaskAppLogger - ERROR - Error deleting log 65: Class 'builtins.int' is not mapped
2024-12-03 20:18:55,476 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:55,995 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:56,179 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:56,346 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:56,550 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:56,717 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:56,924 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:57,095 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:57,292 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:57,545 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:57,721 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:57,827 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:18:58,022 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-03 20:19:29,771 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 20:19:29,779 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:36:57,130 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:36:57,136 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:36:58,546 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:36:58,560 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:37:15,363 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 10:37:17,896 - FlaskAppLogger - ERROR - Error deleting log 65: Class 'builtins.int' is not mapped
2024-12-04 10:37:44,914 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:37:44,922 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:37:52,755 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 10:37:54,790 - FlaskAppLogger - ERROR - Error deleting log 65: Class 'builtins.int' is not mapped
2024-12-04 10:41:32,904 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:41:32,913 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:41:55,280 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 10:41:59,074 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:41:59,086 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:42:06,439 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:42:06,448 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:42:07,924 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:42:07,934 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:42:10,691 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 10:42:12,579 - FlaskAppLogger - ERROR - Error deleting log 67: Class 'builtins.int' is not mapped
2024-12-04 10:45:06,778 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:45:06,787 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:51:13,512 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:51:13,519 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:51:14,921 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:51:14,931 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:51:18,781 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 10:51:21,429 - FlaskAppLogger - ERROR - Error deleting log 65: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'username'
[SQL: SELECT * FROM weather_data WHERE log.username = %(username)s AND id = %(id)s]
[parameters: [{'id': 65}]]
(Background on this error at: https://sqlalche.me/e/14/cd3x)
2024-12-04 10:51:24,947 - FlaskAppLogger - ERROR - Error deleting log 67: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'username'
[SQL: SELECT * FROM weather_data WHERE log.username = %(username)s AND id = %(id)s]
[parameters: [{'id': 67}]]
(Background on this error at: https://sqlalche.me/e/14/cd3x)
2024-12-04 10:51:47,863 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:51:47,871 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:51:53,322 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:51:53,334 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:52:00,522 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:52:00,528 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:52:04,691 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:52:04,695 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:52:13,291 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:52:13,295 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:52:15,388 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 10:52:17,509 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 66
2024-12-04 10:52:29,929 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 67
2024-12-04 10:52:30,235 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 68
2024-12-04 10:52:30,674 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 66
2024-12-04 10:52:31,125 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 10:53:03,169 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 10:53:18,443 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 67
2024-12-04 10:53:48,565 - FlaskAppLogger - ERROR - Error deleting log 67: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2024-12-04 10:53:51,134 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:53:51,139 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:53:53,924 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 10:53:56,584 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 66
2024-12-04 10:56:34,037 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:56:34,040 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:56:35,343 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 10:56:35,349 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 10:57:22,942 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 10:57:25,893 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 10:57:26,139 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 10:57:26,314 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 11:02:30,219 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 11:06:45,184 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 11:06:45,191 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 11:06:52,278 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 11:06:55,988 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 11:07:01,598 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 11:37:17,703 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 11:37:17,972 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 11:37:18,128 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 11:41:31,529 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 11:41:31,533 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 11:41:32,853 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 11:41:32,861 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 11:41:36,726 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 11:41:39,172 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 65
2024-12-04 11:42:02,538 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 67
2024-12-04 12:36:28,565 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 12:36:28,569 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 12:36:29,925 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 12:36:29,931 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 12:36:37,347 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-04 12:36:52,453 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:36:54,441 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:36:56,442 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:36:58,448 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:00,449 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:02,440 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:04,433 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:04,442 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:05,614 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 49, 'pressure': 1010, 'temp': 32.99, 'weather_condition': 'Smoke', 'wind_degree': 100, 'wind_speed': 4.12}
2024-12-04 12:37:05,680 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:06,441 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:06,613 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 49, 'pressure': 1010, 'temp': 32.99, 'weather_condition': 'Smoke', 'wind_degree': 100, 'wind_speed': 4.12}
2024-12-04 12:37:06,623 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:07,732 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 49, 'pressure': 1010, 'temp': 32.99, 'weather_condition': 'Smoke', 'wind_degree': 100, 'wind_speed': 4.12}
2024-12-04 12:37:07,742 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:08,446 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:08,694 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 49, 'pressure': 1010, 'temp': 32.99, 'weather_condition': 'Smoke', 'wind_degree': 100, 'wind_speed': 4.12}
2024-12-04 12:37:08,702 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:09,822 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 49, 'pressure': 1010, 'temp': 32.99, 'weather_condition': 'Smoke', 'wind_degree': 100, 'wind_speed': 4.12}
2024-12-04 12:37:09,831 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:10,445 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:10,741 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 49, 'pressure': 1010, 'temp': 32.99, 'weather_condition': 'Smoke', 'wind_degree': 100, 'wind_speed': 4.12}
2024-12-04 12:37:10,750 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:11,812 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 49, 'pressure': 1010, 'temp': 32.99, 'weather_condition': 'Smoke', 'wind_degree': 100, 'wind_speed': 4.12}
2024-12-04 12:37:11,822 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 12:37:12,934 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 49, 'pressure': 1010, 'temp': 32.99, 'weather_condition': 'Smoke', 'wind_degree': 100, 'wind_speed': 4.12}
2024-12-04 12:46:48,242 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 12:46:48,245 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 12:46:49,504 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 12:46:49,509 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 12:46:54,419 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-04 13:25:34,460 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:25:34,468 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:25:35,791 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:25:35,810 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:25:38,994 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-04 13:25:44,776 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-04 13:25:46,967 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 13:26:12,725 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:26:12,734 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:26:14,148 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:26:14,166 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:26:17,027 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 13:27:35,206 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:27:35,216 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:27:40,583 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:27:40,590 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:27:51,020 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 13:30:28,920 - FlaskAppLogger - INFO - User Anmol deleted weather log with id: 68
2024-12-04 13:39:36,931 - FlaskAppLogger - INFO - User Anmol deleted all weather logs.
2024-12-04 13:39:46,790 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:47,793 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:47,879 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:48,827 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:48,853 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:49,749 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:49,767 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:50,702 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:50,731 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:51,667 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:51,687 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:52,633 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:52,656 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:53,583 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:53,600 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:54,550 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:54,568 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:55,468 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:55,488 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:56,383 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:56,398 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:57,273 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:57,303 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:58,234 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:58,258 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:39:59,188 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:39:59,205 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:00,147 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:00,165 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:01,025 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:01,039 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:01,864 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:01,880 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:02,787 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:02,801 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:03,782 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:03,797 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:04,666 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:04,693 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:05,542 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:05,570 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:06,421 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:06,444 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:07,305 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:07,323 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:08,270 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:08,284 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:09,343 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:09,367 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:40:10,422 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 130, 'wind_speed': 2.57}
2024-12-04 13:40:15,523 - FlaskAppLogger - INFO - User Anmol deleted all weather logs.
2024-12-04 13:40:15,581 - FlaskAppLogger - INFO - User Anmol deleted all weather logs.
2024-12-04 13:40:49,927 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:40:49,935 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:40:51,929 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 13:40:57,730 - FlaskAppLogger - INFO - User Anmol logged out.
2024-12-04 13:50:28,713 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:50:28,716 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:50:30,057 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:50:30,064 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:50:44,296 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:50:44,299 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:50:45,596 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 13:50:45,602 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 13:51:00,181 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 13:51:24,327 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:25,312 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:25,376 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:26,397 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:26,405 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:27,394 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:27,404 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:28,360 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:28,373 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:29,562 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:29,577 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:30,552 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:30,562 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:31,502 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:31,514 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:32,434 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:32,444 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:33,354 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:33,369 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:34,275 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:34,295 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:35,232 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:35,255 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:36,195 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:36,223 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:37,153 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:37,172 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:38,080 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:38,101 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:39,075 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:39,095 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:40,002 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:40,018 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:40,873 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:40,896 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:41,879 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:41,888 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:42,762 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:42,783 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:43,665 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:43,680 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:44,560 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:44,578 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:45,439 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:45,463 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:46,353 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:46,372 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:47,234 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:47,249 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:48,114 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:48,137 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:48,999 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:49,016 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:49,965 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:49,978 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:50,839 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:50,858 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:51,763 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:51,830 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:51:53,158 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:51:56,982 - FlaskAppLogger - INFO - User Anmol deleted all weather logs.
2024-12-04 13:52:03,772 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:04,752 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:04,822 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:05,877 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:05,893 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:06,835 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:06,853 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:08,080 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:08,099 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:09,034 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:09,055 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:09,961 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:09,981 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:10,998 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:11,023 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:11,915 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:11,962 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:12,832 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:12,850 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:13,763 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:13,787 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:14,795 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:14,810 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:15,678 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:15,694 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:16,602 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:16,617 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:17,521 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:17,549 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:18,470 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:18,495 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:19,363 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:19,374 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:20,315 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:20,337 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:21,321 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:21,343 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:22,279 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:22,292 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:23,192 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:23,212 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:24,115 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:24,127 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:24,995 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:25,009 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:26,193 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:26,215 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:27,077 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:27,107 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:27,997 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:28,012 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:28,874 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 13:52:28,904 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 13:52:29,837 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 46, 'pressure': 1009, 'temp': 33.99, 'weather_condition': 'Smoke', 'wind_degree': 260, 'wind_speed': 1.54}
2024-12-04 15:42:48,666 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 15:42:48,691 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 15:42:50,060 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 15:42:50,066 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 15:42:51,547 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 15:50:32,018 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 15:50:32,022 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 15:50:33,345 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 15:50:33,351 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 16:23:18,492 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 16:23:18,495 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 16:23:19,818 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 16:23:19,829 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 17:06:22,277 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 17:06:22,290 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 17:06:23,670 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 17:06:23,679 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 17:08:33,592 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 17:08:41,007 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 17:10:27,029 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 17:16:14,474 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-04 17:18:21,420 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:34:28,226 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-04 17:34:28,508 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-12-04 17:34:36,416 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-04 17:34:37,993 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-04 17:36:45,518 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:36:47,503 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:36:49,513 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:36:51,518 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:36:53,508 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:36:55,509 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:36:57,510 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:36:59,510 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:01,501 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:03,509 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:05,509 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:07,501 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:09,513 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:11,510 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:13,512 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:15,512 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:17,506 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:19,510 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:21,504 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:23,513 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:25,507 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:27,517 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:29,511 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:31,503 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:33,510 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:35,506 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:37,500 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:37:37,595 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-04 17:37:44,246 - FlaskAppLogger - INFO - Registration attempt for user: anmolchourasia05@gmail.com
2024-12-04 17:37:44,248 - FlaskAppLogger - WARNING - Passwords do not match for user: anmolchourasia05@gmail.com
2024-12-04 17:37:55,297 - FlaskAppLogger - INFO - Registration attempt for user: anmolchourasia05@gmail.com
2024-12-04 17:37:55,603 - FlaskAppLogger - INFO - User registered successfully: anmolchourasia05@gmail.com
2024-12-04 17:38:02,102 - FlaskAppLogger - INFO - Login attempt for user: anmolchourasia05@gmail.com
2024-12-04 17:41:52,032 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-04 17:42:00,185 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:02,137 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:04,140 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:06,144 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:08,979 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:10,133 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:12,144 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:14,131 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:16,137 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:18,138 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:20,134 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:22,134 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:24,142 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:26,133 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:28,139 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:30,140 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:31,014 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-04 17:42:32,136 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:34,087 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-04 17:42:34,142 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:36,138 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:38,138 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:40,133 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:42,159 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 17:42:44,135 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-04 23:03:17,931 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:03:17,938 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:03:19,407 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:03:19,416 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:04:13,119 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:11:36,995 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:11:37,004 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:11:39,985 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:14:46,618 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:14:46,626 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:15:16,495 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:18:15,384 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:18:15,390 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:18:16,837 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:25:30,252 - FlaskAppLogger - INFO - User Anmol logged out.
2024-12-04 23:25:31,191 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:25:40,853 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:25:40,856 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:25:42,400 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:25:42,407 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:25:44,601 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:28:18,899 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:28:18,902 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:28:20,443 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:28:20,448 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:28:21,828 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:31:38,498 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:31:38,506 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:32:20,534 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:34:13,385 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:34:13,389 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:34:14,876 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:34:14,881 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:34:16,036 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:36:37,493 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:36:37,506 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:36:38,954 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:36:38,960 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:36:46,856 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:39:32,069 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:39:32,072 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:39:33,571 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:39:33,577 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:39:35,140 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:41:02,645 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:41:02,649 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:41:04,097 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:41:04,102 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:41:08,914 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:45:09,029 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:45:09,033 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:45:10,576 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:45:10,582 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:45:11,857 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-04 23:46:46,496 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-04 23:46:46,499 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:46:48,467 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-04 23:46:50,365 - FlaskAppLogger - INFO - Login attempt for user: Anmol
