2024-11-27 17:50:09,565 - FlaskAppLogger - WARNING - 404 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-27 17:50:27,607 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 17:50:32,014 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 17:54:58,827 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 17:55:00,012 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 17:55:31,648 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 17:55:58,669 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 17:56:17,317 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 18:10:56,415 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 18:12:51,133 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 18:30:40,833 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 18:45:04,785 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 18:45:11,895 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 18:45:12,836 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 18:59:30,261 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 18:59:31,244 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 18:59:31,525 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 18:59:32,548 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 18:59:34,215 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 18:59:57,908 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 18:59:58,842 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 19:01:14,365 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 19:01:15,271 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 19:03:43,308 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 19:04:57,843 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 19:05:55,894 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 19:05:56,925 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 19:06:37,341 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 19:06:38,405 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 19:06:39,929 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 19:11:04,421 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 19:14:23,989 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 19:21:14,763 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 19:26:28,340 - FlaskAppLogger - WARNING - 404 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-27 19:26:30,636 - FlaskAppLogger - WARNING - 404 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-27 19:27:27,309 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 20:06:36,172 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 20:07:17,630 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 20:07:18,549 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 20:12:57,697 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-27 20:13:44,062 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 20:13:45,018 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 20:17:24,646 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 20:17:25,657 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 20:17:25,665 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-27 20:17:26,618 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-27 20:17:27,602 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 11:59:42,908 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 12:13:42,632 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 12:14:20,274 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 12:21:35,522 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 12:22:14,875 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-11-28 12:22:45,553 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 12:26:09,340 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-11-28 12:26:15,211 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 12:26:15,520 - FlaskAppLogger - WARNING - Failed login attempt for user: Nitkarsh
2024-11-28 12:26:20,379 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 12:26:46,360 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-11-28 12:30:23,222 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 12:38:17,872 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:04:05,970 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-11-28 13:04:06,963 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:05:51,622 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:06:09,195 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-11-28 13:06:11,674 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:06:25,211 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-11-28 13:06:27,839 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-28 13:07:02,106 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 13:07:03,027 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 13:07:03,034 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 13:07:03,916 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 13:07:03,932 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 13:07:04,829 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 13:07:07,400 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 13:07:08,271 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 13:07:22,310 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:10:26,859 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:10:57,667 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:12:05,380 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:16:21,541 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:25:22,828 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:38:14,916 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:39:16,626 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:51:16,106 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:52:13,937 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:53:00,698 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:55:12,984 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 13:59:25,430 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 14:24:27,819 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 14:28:49,592 - FlaskAppLogger - ERROR - Error creating tables: The sqlalchemy extension was not registered to the current application.  Please make sure to call init_app() first.
2024-11-28 14:34:28,837 - FlaskAppLogger - ERROR - Error creating tables: The sqlalchemy extension was not registered to the current application.  Please make sure to call init_app() first.
2024-11-28 14:34:33,856 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:35:34,288 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 14:35:53,789 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:36:03,781 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 14:36:33,393 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:36:37,978 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:36:47,105 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 14:38:00,317 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:38:09,136 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:38:10,050 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:38:18,551 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 14:40:02,992 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:44:03,289 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:44:04,550 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:44:12,960 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 14:44:36,751 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:22:02,180 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:22:03,319 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:22:45,012 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 15:26:56,413 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:27:10,920 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:27:17,240 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:27:57,681 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:28:17,431 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:28:18,548 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:28:51,978 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 15:33:28,030 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:33:29,212 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:34:02,333 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:34:17,099 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:36:19,414 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 15:37:24,999 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 15:38:06,110 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 15:38:13,074 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 15:38:42,438 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 15:43:37,458 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 15:48:01,116 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 15:48:02,373 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 15:48:06,536 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 15:52:04,674 - FlaskAppLogger - INFO - Fetching weather data for city: mumbai
2024-11-28 15:52:05,603 - FlaskAppLogger - INFO - Successfully fetched weather data for city: mumbai
2024-11-28 15:52:05,698 - FlaskAppLogger - INFO - Fetching weather data for city: mumbai
2024-11-28 15:52:06,607 - FlaskAppLogger - INFO - Successfully fetched weather data for city: mumbai
2024-11-28 16:23:07,614 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 16:24:18,480 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 16:27:49,575 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 16:30:48,068 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 16:30:49,205 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 16:30:58,250 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 16:31:50,341 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 17:02:42,665 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 17:02:43,929 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 17:02:53,361 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 18:54:56,842 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 18:58:37,041 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 19:00:34,473 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 19:00:35,682 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_logs" already exists

[SQL: 
CREATE TABLE weather_logs (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	city VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-11-28 19:01:36,682 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:01:50,880 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:01:52,162 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:04:49,667 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:05:00,165 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:05:03,305 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:05:08,103 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:05:12,431 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:09:11,106 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:09:30,881 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:09:33,838 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:09:37,772 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:09:42,290 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:09:46,286 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:14:02,064 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:14:03,190 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:14:18,525 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-11-28 19:14:45,060 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:14:56,913 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:15:08,302 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:15:14,391 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:15:17,914 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:15:21,783 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:15:28,162 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-11-28 19:15:31,293 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-11-28 19:15:37,400 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 19:15:44,729 - FlaskAppLogger - INFO - Session data <SecureCookieSession {'csrf_token': 'f05a07b39afcf44189a0dec88ebb4a41f34fa982', 'username': 'Nitkarsh'}>
2024-11-28 19:16:09,304 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:16:17,796 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:16:23,387 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:16:23,542 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-11-28 19:16:37,097 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:16:41,888 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:16:43,438 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-11-28 19:16:44,467 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-11-28 19:23:56,140 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:31:37,186 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:31:38,569 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:31:39,688 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-11-28 19:33:00,117 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:33:02,815 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:33:05,759 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:33:47,032 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:33:48,322 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:33:51,964 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 19:35:01,295 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:35:02,754 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:35:10,044 - FlaskAppLogger - INFO - Session data <SecureCookieSession {'csrf_token': '4be205031e45227a88c88f091a2da769e7a20b53'}>
2024-11-28 19:35:23,258 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 19:35:54,072 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:36:51,600 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 19:38:00,554 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:38:08,209 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:38:12,511 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:38:37,403 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:40:52,370 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 19:42:53,553 - FlaskAppLogger - INFO - Session data <SecureCookieSession {'csrf_token': 'd4c018172ea4802018e018d0d8e0087900272863', 'username': 'Nitkarsh'}>
2024-11-28 19:50:02,084 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 19:50:03,710 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 19:51:40,230 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:51:41,504 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:51:51,268 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 19:57:31,358 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:57:33,038 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:58:42,397 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:58:47,362 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:58:50,220 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:58:52,124 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:59:02,763 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 19:59:36,735 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 19:59:40,430 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 20:00:03,597 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:00:11,179 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 20:00:43,703 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:00:46,356 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:00:49,316 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:00:53,336 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:01:00,296 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:01:05,265 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 20:06:10,980 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:06:36,709 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:06:38,178 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:06:42,059 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-11-28 20:06:52,498 - FlaskAppLogger - INFO - Session data <SecureCookieSession {'csrf_token': '21d8f0ebfaab68704b4f1b0d02b24f252159746f', 'username': 'Nitkarsh'}>
2024-11-28 20:10:14,873 - FlaskAppLogger - INFO - Session data <SecureCookieSession {'csrf_token': '21d8f0ebfaab68704b4f1b0d02b24f252159746f', 'username': 'Nitkarsh'}>
2024-11-28 20:13:57,365 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:13:58,376 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:20:36,614 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-11-28 20:20:38,947 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-28 20:21:43,453 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:44,391 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:21:44,397 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:45,316 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:21:45,322 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:46,229 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:21:46,235 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:47,111 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:21:47,117 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:47,998 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:21:48,004 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:48,917 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:21:48,924 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:49,785 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:21:49,792 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:51,973 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:21:51,980 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:53,165 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:21:53,171 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:54,081 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:21:54,087 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:21:54,951 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:24:56,380 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:24:57,281 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:06,078 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:06,927 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:07,452 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:08,274 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:10,502 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:11,394 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:11,406 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:12,271 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:12,294 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:13,149 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:13,158 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:13,994 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:14,014 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:15,395 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:15,420 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:16,237 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:16,252 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:17,075 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:17,097 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:17,923 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:17,946 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:18,800 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:18,811 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:19,630 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:19,652 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:20,484 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:24,068 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:24,954 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:24,969 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:25,837 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:25:25,851 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:25:26,683 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:27:31,839 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:27:32,805 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:27:45,951 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:27:46,882 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:27:48,221 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:27:49,156 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:27:49,169 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:27:50,129 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:27:50,170 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:27:51,042 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:27:51,091 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:27:51,961 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:27:51,986 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:27:52,924 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:28:21,117 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:28:22,035 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:28:40,141 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:28:41,128 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:28:50,293 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:28:51,158 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:28:51,178 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:28:52,046 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:28:52,061 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:28:53,244 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:29:21,182 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-11-28 20:29:22,078 - FlaskAppLogger - INFO - Successfully fetched weather data for city: Mumbai
2024-11-28 20:36:15,696 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:36:16,951 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:36:26,885 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-28 20:37:17,851 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:37:42,732 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:40:33,881 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:40:46,905 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-28 20:45:32,945 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:45:34,247 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:45:35,709 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-28 20:48:46,619 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:48:47,825 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:48:51,693 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-28 20:52:49,953 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:53:45,130 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:53:46,490 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:53:51,076 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-28 20:54:50,482 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:54:51,863 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 20:55:00,899 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-28 20:59:57,715 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 21:00:00,514 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 21:00:24,061 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 21:00:25,385 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 21:00:32,816 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-28 21:00:49,051 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 21:00:50,658 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-28 21:01:48,982 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 21:01:50,194 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-28 21:01:58,932 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-29 16:47:18,035 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-29 16:47:19,452 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-30 12:12:09,205 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-30 12:12:10,822 - FlaskAppLogger - INFO - Tables created successfully.
2024-11-30 12:12:18,564 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-11-30 12:12:32,947 - FlaskAppLogger - INFO - User Anmol logged out.
2024-11-30 12:12:39,890 - FlaskAppLogger - INFO - Login attempt for user: Anmol
2024-12-01 17:51:50,981 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-01 17:51:52,582 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-01 17:54:52,077 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-02 15:37:18,266 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 15:37:19,699 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 15:37:39,640 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-02 15:39:07,941 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 15:39:12,590 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-02 15:55:12,646 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 15:55:18,348 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 15:55:30,630 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 15:55:44,484 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 15:56:01,074 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 15:58:42,548 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 15:58:44,497 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 15:58:47,979 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-02 16:15:51,295 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 16:15:55,141 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 16:16:16,461 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 16:16:18,997 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 16:16:19,834 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 16:17:34,108 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 16:17:38,125 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 16:17:43,919 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 16:17:49,135 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 16:18:03,422 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 16:18:10,037 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 16:18:14,368 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 16:18:21,082 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 16:59:17,988 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 17:00:30,941 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 17:01:07,807 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 17:01:08,982 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 17:01:09,978 - FlaskAppLogger - INFO - Fetching weather data for city: [object HTMLInputElement]
2024-12-02 17:01:15,593 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-02 17:03:45,269 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:03:52,998 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-02 17:05:30,583 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 17:05:31,985 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 17:05:44,573 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-02 17:07:14,512 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:07:53,077 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:08:29,124 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai, Maharashtra
2024-12-02 17:08:41,846 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-02 17:14:54,188 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-02 17:14:59,797 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:15:30,788 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:16:47,790 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:25:51,878 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:27:37,510 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:27:57,868 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:35:13,020 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 17:35:14,389 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 17:35:19,062 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-02 17:35:22,135 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:40:25,074 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 17:40:26,471 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-02 17:40:29,703 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-02 17:40:32,590 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:40:56,005 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:41:02,244 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-02 17:41:10,742 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-02 17:41:11,937 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-02 17:41:34,397 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:43:16,924 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:43:18,096 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:43:22,660 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-02 17:45:02,076 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:45:03,051 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:49:04,827 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:49:06,731 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:49:08,168 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:49:09,058 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:50:22,923 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:50:23,823 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:55:47,860 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:56:25,644 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:56:30,243 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-02 17:57:45,899 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:57:47,459 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-02 17:57:52,923 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-02 18:06:49,291 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 10:44:28,250 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 10:44:29,747 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 10:44:33,586 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 10:44:39,387 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 10:44:54,556 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 10:53:01,899 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 10:55:06,094 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 10:55:41,765 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 10:57:36,216 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 10:57:37,707 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 10:57:39,311 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 10:57:41,067 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-03 10:58:21,709 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 10:58:25,709 - FlaskAppLogger - INFO - User Nitkarsh logged out.
2024-12-03 10:59:27,485 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 11:01:24,219 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 11:05:50,370 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 11:05:51,809 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 11:10:50,290 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 11:10:51,686 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 11:11:44,275 - FlaskAppLogger - ERROR - Error creating tables: name 'WeatherLog' is not defined
2024-12-03 11:11:44,276 - FlaskAppLogger - INFO - Tables created successfully by Engine.
2024-12-03 11:13:38,968 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:13:38,970 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:16:56,019 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 11:16:57,441 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 11:17:14,092 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 11:17:19,517 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:17:19,525 - FlaskAppLogger - INFO - Tables created successfully by Engine.
2024-12-03 11:17:21,098 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:17:21,110 - FlaskAppLogger - INFO - Tables created successfully by Engine.
2024-12-03 11:17:40,883 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:17:40,893 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:17:50,606 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:17:50,607 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:18:28,287 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:18:28,298 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:18:31,390 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:18:31,392 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:18:31,394 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:18:53,702 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:18:53,711 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:18:58,708 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:18:58,716 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:19:09,048 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:19:09,058 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:21:02,764 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:21:02,788 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:21:04,221 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:21:04,231 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:21:07,070 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:21:07,072 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:21:07,076 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:21:39,071 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:21:39,082 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:21:40,508 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:21:40,518 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:21:46,773 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:21:46,776 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:23:51,776 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:23:51,783 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:25:43,884 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:25:43,888 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:25:45,482 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:25:45,487 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:25:48,145 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:25:48,146 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:26:00,193 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:26:00,201 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:26:00,373 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:26:00,374 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:26:00,377 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:26:02,987 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:26:02,995 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:26:05,060 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:26:05,061 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:26:05,063 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:28:03,001 - FlaskAppLogger - INFO - Tables created successfully.
2024-12-03 11:28:04,442 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:28:04,451 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:28:20,075 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:28:20,077 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:28:20,080 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:28:22,971 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:28:22,973 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:28:22,977 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:28:23,861 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:28:23,861 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:28:23,866 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:28:44,707 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:28:44,708 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:28:44,715 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:28:59,098 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:28:59,105 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:28:59,279 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:28:59,280 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:28:59,284 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:31:17,400 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 11:31:35,014 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:31:35,015 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:31:35,018 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:41:22,262 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:41:22,265 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:41:23,739 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:41:23,747 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:41:29,469 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 11:41:29,470 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 11:41:29,475 - FlaskAppLogger - INFO - Recieved data: (<Response 44 bytes [200 OK]>, 400)
2024-12-03 11:41:29,480 - FlaskAppLogger - WARNING - Invalid data received: 'Key country_name not found in data'
2024-12-03 11:42:44,389 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 11:42:45,341 - FlaskAppLogger - INFO - Recieved data: <Response 182 bytes [200 OK]>
2024-12-03 11:42:45,343 - FlaskAppLogger - ERROR - Error saving data to database: argument of type 'Response' is not iterable
2024-12-03 11:47:45,710 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:47:45,716 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:47:46,132 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 11:47:47,116 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1011, 'temp': 30.99, 'weather_condition': 'Smoke', 'wind_degree': 20, 'wind_speed': 2.57}
2024-12-03 11:47:47,227 - FlaskAppLogger - ERROR - Error saving data to database: (psycopg2.errors.NotNullViolation) null value in column "username" of relation "weather_data" violates not-null constraint
DETAIL:  Failing row contains (1, null, IN, Mumbai, Smoke, 30.99, 1011, 48, 2.57, 20, 2024-12-03 11:47:47.117034+05:30).

[SQL: INSERT INTO weather_data (username, country_name, city_name, weather_condition, temperature, pressure, humidity, wind_speed, wind_degree, timestamp) VALUES (%(username)s, %(country_name)s, %(city_name)s, %(weather_condition)s, %(temperature)s, %(pressure)s, %(humidity)s, %(wind_speed)s, %(wind_degree)s, %(timestamp)s) RETURNING weather_data.id]
[parameters: {'username': None, 'country_name': 'IN', 'city_name': 'Mumbai', 'weather_condition': 'Smoke', 'temperature': 30.99, 'pressure': 1011, 'humidity': 48, 'wind_speed': 2.57, 'wind_degree': 20, 'timestamp': datetime.datetime(2024, 12, 3, 6, 17, 47, 117034, tzinfo=datetime.timezone.utc)}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2024-12-03 11:47:57,268 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 11:47:58,192 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1011, 'temp': 30.99, 'weather_condition': 'Smoke', 'wind_degree': 20, 'wind_speed': 2.57}
2024-12-03 11:47:58,200 - FlaskAppLogger - ERROR - Error saving data to database: (psycopg2.errors.NotNullViolation) null value in column "username" of relation "weather_data" violates not-null constraint
DETAIL:  Failing row contains (2, null, IN, Mumbai, Smoke, 30.99, 1011, 48, 2.57, 20, 2024-12-03 11:47:58.193142+05:30).

[SQL: INSERT INTO weather_data (username, country_name, city_name, weather_condition, temperature, pressure, humidity, wind_speed, wind_degree, timestamp) VALUES (%(username)s, %(country_name)s, %(city_name)s, %(weather_condition)s, %(temperature)s, %(pressure)s, %(humidity)s, %(wind_speed)s, %(wind_degree)s, %(timestamp)s) RETURNING weather_data.id]
[parameters: {'username': None, 'country_name': 'IN', 'city_name': 'Mumbai', 'weather_condition': 'Smoke', 'temperature': 30.99, 'pressure': 1011, 'humidity': 48, 'wind_speed': 2.57, 'wind_degree': 20, 'timestamp': datetime.datetime(2024, 12, 3, 6, 17, 58, 193142, tzinfo=datetime.timezone.utc)}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2024-12-03 11:48:14,205 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:48:14,216 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:48:19,367 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:48:19,378 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:48:21,323 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 11:48:22,307 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1011, 'temp': 30.99, 'weather_condition': 'Smoke', 'wind_degree': 20, 'wind_speed': 2.57}
2024-12-03 11:48:22,310 - FlaskAppLogger - WARNING - Invalid data received: 'username'
2024-12-03 11:48:31,359 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 11:48:32,308 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1011, 'temp': 30.99, 'weather_condition': 'Smoke', 'wind_degree': 20, 'wind_speed': 2.57}
2024-12-03 11:48:32,310 - FlaskAppLogger - WARNING - Invalid data received: 'username'
2024-12-03 11:49:07,108 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:49:07,115 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:49:16,574 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 11:49:17,469 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1011, 'temp': 30.99, 'weather_condition': 'Smoke', 'wind_degree': 20, 'wind_speed': 2.57}
2024-12-03 11:49:17,471 - FlaskAppLogger - ERROR - Error saving data to database: name 'username' is not defined
2024-12-03 11:49:49,229 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 11:50:29,060 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:50:29,069 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:50:29,487 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 11:50:30,385 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1011, 'temp': 30.99, 'weather_condition': 'Smoke', 'wind_degree': 20, 'wind_speed': 2.57}
2024-12-03 11:50:30,393 - FlaskAppLogger - ERROR - Error saving data to database: (psycopg2.ProgrammingError) can't adapt type 'LocalProxy'
[SQL: INSERT INTO weather_data (username, country_name, city_name, weather_condition, temperature, pressure, humidity, wind_speed, wind_degree, timestamp) VALUES (%(username)s, %(country_name)s, %(city_name)s, %(weather_condition)s, %(temperature)s, %(pressure)s, %(humidity)s, %(wind_speed)s, %(wind_degree)s, %(timestamp)s) RETURNING weather_data.id]
[parameters: {'username': <SecureCookieSession {}>, 'country_name': 'IN', 'city_name': 'Mumbai', 'weather_condition': 'Smoke', 'temperature': 30.99, 'pressure': 1011, 'humidity': 48, 'wind_speed': 2.57, 'wind_degree': 20, 'timestamp': datetime.datetime(2024, 12, 3, 6, 20, 30, 387913, tzinfo=datetime.timezone.utc)}]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:51:00,193 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:51:00,203 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:51:05,261 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:51:05,267 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:51:54,733 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 11:51:55,710 - FlaskAppLogger - WARNING - Invalid data received: 'username'
2024-12-03 11:52:21,539 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:52:21,545 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:52:22,087 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 11:52:23,000 - FlaskAppLogger - WARNING - Invalid data received: 'username'
2024-12-03 11:55:59,371 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:55:59,375 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:56:01,098 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:56:01,105 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:56:02,012 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 11:56:02,956 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1011, 'temp': 30.99, 'weather_condition': 'Smoke', 'wind_degree': 20, 'wind_speed': 2.57}
2024-12-03 11:56:02,971 - FlaskAppLogger - ERROR - Error saving data to database: (psycopg2.errors.NotNullViolation) null value in column "username" of relation "weather_data" violates not-null constraint
DETAIL:  Failing row contains (3, null, IN, Mumbai, Smoke, 30.99, 1011, 48, 2.57, 20, 2024-12-03 11:56:02.959935+05:30).

[SQL: INSERT INTO weather_data (username, country_name, city_name, weather_condition, temperature, pressure, humidity, wind_speed, wind_degree, timestamp) VALUES (%(username)s, %(country_name)s, %(city_name)s, %(weather_condition)s, %(temperature)s, %(pressure)s, %(humidity)s, %(wind_speed)s, %(wind_degree)s, %(timestamp)s) RETURNING weather_data.id]
[parameters: {'username': None, 'country_name': 'IN', 'city_name': 'Mumbai', 'weather_condition': 'Smoke', 'temperature': 30.99, 'pressure': 1011, 'humidity': 48, 'wind_speed': 2.57, 'wind_degree': 20, 'timestamp': datetime.datetime(2024, 12, 3, 6, 26, 2, 959935, tzinfo=datetime.timezone.utc)}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2024-12-03 11:57:29,951 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:58:31,501 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:58:40,072 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:58:40,075 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:58:41,592 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:58:41,599 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:58:41,781 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:58:43,204 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:58:44,009 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:58:44,577 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:58:44,796 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:58:45,008 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:59:00,790 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:59:12,074 - FlaskAppLogger - INFO - Session data <SecureCookieSession {'csrf_token': '38f369571f7a24c8a342b3c281a63dc8ca009f2a'}>
2024-12-03 11:59:28,074 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 11:59:28,079 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 11:59:28,256 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:59:29,169 - FlaskAppLogger - INFO - Session data <SecureCookieSession {}>
2024-12-03 11:59:36,444 - FlaskAppLogger - INFO - Session data <SecureCookieSession {'csrf_token': '32695d966bb434f9f5ddbdaeccccfde722aa04f8'}>
2024-12-03 12:00:27,177 - FlaskAppLogger - INFO - Session data <SecureCookieSession {'csrf_token': '32695d966bb434f9f5ddbdaeccccfde722aa04f8'}>
2024-12-03 12:01:19,640 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:01:19,645 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:01:56,199 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:01:56,202 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:01:57,619 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:01:57,623 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:02:04,281 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 12:02:04,282 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 12:02:04,285 - FlaskAppLogger - ERROR - Error saving data to database: 'tuple' object has no attribute 'json'
2024-12-03 12:02:16,815 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 12:02:16,817 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 12:02:16,822 - FlaskAppLogger - ERROR - Error saving data to database: 'tuple' object has no attribute 'json'
2024-12-03 12:02:18,784 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 12:02:18,786 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 12:02:18,788 - FlaskAppLogger - ERROR - Error saving data to database: 'tuple' object has no attribute 'json'
2024-12-03 12:02:19,117 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 12:02:19,118 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 12:02:19,120 - FlaskAppLogger - ERROR - Error saving data to database: 'tuple' object has no attribute 'json'
2024-12-03 12:02:19,421 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 12:02:19,422 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 12:02:19,424 - FlaskAppLogger - ERROR - Error saving data to database: 'tuple' object has no attribute 'json'
2024-12-03 12:02:19,734 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 12:02:19,736 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 12:02:19,738 - FlaskAppLogger - ERROR - Error saving data to database: 'tuple' object has no attribute 'json'
2024-12-03 12:02:20,025 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 12:02:20,027 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 12:02:20,036 - FlaskAppLogger - ERROR - Error saving data to database: 'tuple' object has no attribute 'json'
2024-12-03 12:02:29,574 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:02:30,491 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 30.99, 'weather_condition': 'Smoke', 'wind_degree': 20, 'wind_speed': 2.57}
2024-12-03 12:02:30,505 - FlaskAppLogger - ERROR - Error saving data to database: (psycopg2.errors.NotNullViolation) null value in column "username" of relation "weather_data" violates not-null constraint
DETAIL:  Failing row contains (4, null, IN, Mumbai, Smoke, 30.99, 1009, 48, 2.57, 20, 2024-12-03 12:02:30.493167+05:30).

[SQL: INSERT INTO weather_data (username, country_name, city_name, weather_condition, temperature, pressure, humidity, wind_speed, wind_degree, timestamp) VALUES (%(username)s, %(country_name)s, %(city_name)s, %(weather_condition)s, %(temperature)s, %(pressure)s, %(humidity)s, %(wind_speed)s, %(wind_degree)s, %(timestamp)s) RETURNING weather_data.id]
[parameters: {'username': None, 'country_name': 'IN', 'city_name': 'Mumbai', 'weather_condition': 'Smoke', 'temperature': 30.99, 'pressure': 1009, 'humidity': 48, 'wind_speed': 2.57, 'wind_degree': 20, 'timestamp': datetime.datetime(2024, 12, 3, 6, 32, 30, 493167, tzinfo=datetime.timezone.utc)}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2024-12-03 12:04:28,012 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:04:28,017 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:04:40,779 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 12:04:47,689 - FlaskAppLogger - INFO - Fetching weather data for city: London
2024-12-03 12:06:26,803 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:06:26,806 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:06:28,319 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:06:28,326 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:06:29,706 - FlaskAppLogger - INFO - Recieved data: None
2024-12-03 12:06:29,707 - FlaskAppLogger - ERROR - Error saving data to database: argument of type 'NoneType' is not iterable
2024-12-03 12:06:44,358 - FlaskAppLogger - INFO - Recieved data: None
2024-12-03 12:06:44,359 - FlaskAppLogger - ERROR - Error saving data to database: argument of type 'NoneType' is not iterable
2024-12-03 12:06:52,557 - FlaskAppLogger - INFO - Recieved data: None
2024-12-03 12:06:52,558 - FlaskAppLogger - ERROR - Error saving data to database: argument of type 'NoneType' is not iterable
2024-12-03 12:07:58,320 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:07:58,325 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:07:59,864 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:07:59,874 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:08:00,805 - FlaskAppLogger - INFO - Recieved data: None
2024-12-03 12:08:00,806 - FlaskAppLogger - ERROR - Error saving data to database: argument of type 'NoneType' is not iterable
2024-12-03 12:08:19,492 - FlaskAppLogger - INFO - Login attempt for user: Nitkarsh
2024-12-03 12:08:51,704 - FlaskAppLogger - INFO - Fetching weather data for city: None
2024-12-03 12:08:51,707 - FlaskAppLogger - WARNING - City parameter is missing in weather fetch request
2024-12-03 12:08:51,708 - FlaskAppLogger - ERROR - Error saving data to database: 'tuple' object has no attribute 'json'
2024-12-03 12:08:57,713 - FlaskAppLogger - INFO - Fetching weather data for city: Mumbai
2024-12-03 12:08:58,645 - FlaskAppLogger - INFO - Recieved data: {'city_name': 'Mumbai', 'country_name': 'IN', 'humidity': 48, 'pressure': 1009, 'temp': 30.99, 'weather_condition': 'Smoke', 'wind_degree': 20, 'wind_speed': 2.57}
2024-12-03 12:25:19,441 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:25:19,446 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:25:20,925 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:25:20,931 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:25:22,144 - FlaskAppLogger - INFO - Recieved data: None
2024-12-03 12:25:22,145 - FlaskAppLogger - ERROR - Error saving data to database: argument of type 'NoneType' is not iterable
2024-12-03 12:25:58,690 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:25:58,694 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:26:00,409 - FlaskAppLogger - ERROR - Error creating tables: (psycopg2.errors.DuplicateTable) relation "weather_data" already exists

[SQL: 
CREATE TABLE weather_data (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	country_name VARCHAR(100) NOT NULL, 
	city_name VARCHAR(100) NOT NULL, 
	weather_condition VARCHAR(100) NOT NULL, 
	temperature FLOAT NOT NULL, 
	pressure INTEGER NOT NULL, 
	humidity INTEGER NOT NULL, 
	wind_speed FLOAT NOT NULL, 
	wind_degree FLOAT NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2024-12-03 12:26:00,438 - FlaskAppLogger - INFO - Error thrown successfully.
2024-12-03 12:26:00,976 - FlaskAppLogger - ERROR - Error saving data to database: name 'user_name' is not defined
